### ISSUE TITLE
白嫖知乎不太体面吧

### ISSUE THREAD

**Issue by asdasd1dsadsa** [koishijs/koishi-plugin-tex#1]
有机会还是得整个pdflatex的环境，编译一份standalone类型的

**Comment by shigma** [comment]
**除了知乎以外还有不少网站是专门提供 latex 编译的，也可以换成那些网站**。而考虑到国内访问速度我才选择了知乎。

**本质上这些网站都是对外公开这些 API 的，并且在用户协议中也没有说明这是禁止的**（如果有的话我会进行更换）。我的所有源代码都遵循开源许可证和相关法律，并且愿意接受监督，不存在白嫖不体面的说法。

而本地环境我觉得那就完全是另一个插件的事情了，如果你想贡献一个新插件的话我将无比欢迎。

不知道你怎么看呢？

**Comment by asdasd1dsadsa** [comment]
所以我用的是「不太体面」这个词，应该还算温和。

本地版本的确实原则上应该是新插件，半年后得闲了会搞机器人，那时候可能动手搞吧。

**Comment by shigma** [comment]
支持。

**Comment by rnotlnglgq** [comment]
js新手，凑合摸了一份 https://github.com/rnotlnglgq/koishi-plugin-tex-local

**Comment by shigma** [comment]
> js新手，凑合摸了一份 [rnotlnglgq/koishi-plugin-tex-local](https://github.com/rnotlnglgq/koishi-plugin-tex-local)

好好好，支持
